#!/bin/bash

./save_view -h 'http://b3egmne1lua9q8qh.couchbase.clvrcld.net:8091/couchBase/b3egmne1lua9q8qh/_design' -u b3egmne1lua9q8qh -p 3ce73caf102548ac806b11067c146590 -f book.ddoc -d book

./save_view -h 'http://b3egmne1lua9q8qh.couchbase.clvrcld.net:8091/couchBase/b3egmne1lua9q8qh/_design' -u b3egmne1lua9q8qh -p 3ce73caf102548ac806b11067c146590 -f comments.ddoc -d comments

./save_view -h 'http://b3egmne1lua9q8qh.couchbase.clvrcld.net:8091/couchBase/b3egmne1lua9q8qh/_design' -u b3egmne1lua9q8qh -p 3ce73caf102548ac806b11067c146590 -f ezb.ddoc -d ezb

./save_view -h 'http://b3egmne1lua9q8qh.couchbase.clvrcld.net:8091/couchBase/b3egmne1lua9q8qh/_design' -u b3egmne1lua9q8qh -p 3ce73caf102548ac806b11067c146590 -f layer.ddoc -d layer

./save_view -h 'http://b3egmne1lua9q8qh.couchbase.clvrcld.net:8091/couchBase/b3egmne1lua9q8qh/_design' -u b3egmne1lua9q8qh -p 3ce73caf102548ac806b11067c146590 -f projects.ddoc -d projects

./save_view -h 'http://b3egmne1lua9q8qh.couchbase.clvrcld.net:8091/couchBase/b3egmne1lua9q8qh/_design' -u b3egmne1lua9q8qh -p 3ce73caf102548ac806b11067c146590 -f votes.ddoc -d votes
