#!/bin/bash

# Arguments = -u username -p password -f file -d desing-document

usage()
{
cat << EOF
usage: $0 options

This script sends a design document to the localhost Couchbase

Required Parameters:
    -u    The administrator user name
    -p    The administrator password
    -f    File containing the desing document
    -d    Name of the design document in the database
EOF
}

USER=
PASSWD=
FILE=
DDOC=
while getopts "u:p:f:d:" OPTION
do
    case $OPTION in
        u)
            CUSER=$OPTARG
            ;;
        p)
            CPASSWD=$OPTARG
            ;;
        f)
            CFILE=$OPTARG
            ;;
        d)
            CDDOC=$OPTARG
            ;;
        *)
            usage
            exit
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ -n "$CUSER" ] && [ -n "$CPASSWD" ] && [ -n "$CFILE" ] && [ -n "$CDDOC" ]
then
    curl -u $CUSER:"$CPASSWD" -X PUT -H 'Content-Type: application/json' 'http://127.0.0.1:8092/ezoom-books/_design/'$CDDOC -d @$CFILE
else
    echo "Oops! empty parameters"
    usage
    exit
fi


